export { default as Home } from "@/pages/Home";
export { default as PostCreatePage } from "@/pages/PostCreate";
export { default as PostUpdatePage } from "@/pages/PostUpdate";
export { default as ErrorPage } from "@/pages/Error";
export { default as Signup } from "@/pages/Signup";
export { default as Login } from "@/pages/Login";
export { default as Profile } from "@/pages/Profile";
export { default as CommunityPage } from "./Community";
export { default as PostDetailPage } from "./PostDetail";
